title: dynamodb
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for dynamodb databases monitored with the AWS integration
icon:
    name: dynamodb
    background: "#3368A2"
    foreground: white
