title: php-fpm
author: Dataloop.IO
version: 1.0.0
description: Scrapes the php-fpm status page for metrics
instructions_required: true
icon:
    name: process
    background: "#8993BE"
    foreground: white
