title: autoscaling
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for autoscaling groups monitored with the AWS integration
icon:
    name: aws
    background: "#F88D00"
    foreground: white
