title: MongoDB
author: Dataloop.IO
version: 1.0.1
processes:
    - mongo
    - mongod
description: Every metric from mongostat
icon:
    name: mongodb
    background: "#343637"
    foreground: "#63B43D"
