title: Java
author: Dataloop.IO
version: 1.0.0
description: Monitors Java processes on local machine via JMX
instructions_required: true
icon:
    name: java
    background: "#EA6F00"
    foreground: "#002A39"
