title: Elasticsearch
author: Dataloop.IO
version: 1.0.1
processes:
    - elasticsearch
description: Queries the stats and health endpoints for all Elasticsearch metrics
icon:
    name: elasticsearch
    background: "#38BFB0"
    foreground: "#231F20"
