title: opsworks
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for OpsWorks stacks monitored with the AWS integration
icon:
    name: aws
    background: "#769A3E"
    foreground: white
