title: Postgres
author: Dataloop.IO
version: 1.0.3
processes:
    - postgres
description: Postgres availability and performance monitoring. You will need to edit the postgres.py plugin to specify settings.
icon:
    name: postgres
    background: "#336791"
    foreground: white
