title: redshift
author: Dataloop.IO
version: 1.0.0
description: Dashboards and alert rules for redshift monitored with the AWS integration
icon:
    name: redshift
    background: "#2D72B8"
    foreground: white
